@Catalog_HostAddress = https://localhost:7213/products

GET {{Catalog_HostAddress}}
Accept: application/json

###

GET {{Catalog_HostAddress}}/1
Accept: application/json

###

POST {{Catalog_HostAddress}}/
Content-Type: application/json
{
    "id": 10,
    "name": "new Swn Flash",
    "Description": "A new product",
    "Price": 62.99,
    "ImageUrl": "product10.png"
}
###

PUT {{Catalog_HostAddress}}/10
Content-Type: application/json
{
    "id": 10,
    "name": "UPDATED Swn Flash",
    "Description": "A new product",
    "Price": 70.99,
    "ImageUrl": "product10.png"
}
###

DELETE {{Catalog_HostAddress}}/10
Content-Type: application/json

###